Async volume creation
concourse/baggageclaim pull request #9
Opened 2017-07-17 12:24 UTC by SHyx0rmZ

2017-07-26 21:01 UTC, jtarchie commented
@SHyx0rmZ, thanks for the PR. I've been spending the afternoon investigating (poking) it.

1. Ran it locally with a bosh virtualbox deployed concourse. It works with some example pipelines [1][2]. 
2. Ran [testflight] against the deployment. The test that exercises `timeout` on a task failed. Its total runtime was *1766.798* seconds. For reference, it takes *734.361* seconds without your changes.
3. Reran the test with `timeout` several time and 4/5 times it failed. The one time it passed it took *27* seconds. The same test without your changes passes consistently at *~11* seconds.

I don't have any reference if it is more stable, but things are definitely taking longer. Going to dive into more.

[1] https://github.com/concourse/testflight/blob/master/pipelines/fixtures/do.yml
[2] https://github.com/concourse/testflight/blob/master/pipelines/fixtures/simple.yml

2017-08-09 16:10 UTC, vito commented
Awesome, thanks for doing this!

A couple things:

1. I think we can hide all this under the existing client-side API. We don't have a use case for exposing async creation up to the client, I don't think. Can we have `CreateVolume` on the client just do the async create + wait under the hood?
1. I'm guessing what @jtarchie found with the tests slowing down could be due to there always being the initial polling delay added to every volume create. Could we do an exponential backoff up to 10 seconds instead?

2017-08-11 10:59 UTC, SHyx0rmZ commented on client/volume_future.go
> +			time.Sleep(10 * time.Second)
Do exponential back-off here.

2017-08-11 11:04 UTC, SHyx0rmZ commented
Personally, I feel like I wouldn't want to force this onto all existing clients, which is why I exposed new routes. This partly stems from the fact that I'm not sure that this is the right thing to do. I can't clearly see how this will resolve the timeout problem, yet.

On a (side) note: The community recently came up with the idea of adding a possibility to narrow down the set of artifacts (or paths within them) that will have to be copied to reduce the time until the response. Maybe that idea obsoletes this pull request?

2017-08-15 23:37 UTC, SHyx0rmZ commented
@vito I updated the pull request with what I understood were the changes you suggested. I feel like I might have misunderstood exactly what you envisioned when you suggested to hide everything under the existing client-side API.

The functionality is still done inside the client, but it's no longer exposed in the Client interface. I figured we would still have to do it in the client, because this is about the HTTP requests after all.

If we want to expose the asynchronous version through the `POST /volumes` handler and get rid of the synchronous version I'd also suggest moving the routes for the future to `/promise` or `/future`.

If there still is anything I can do or you had some smart idea about all of this, let me know!

2017-08-16 00:36 UTC, vito requested changes
@SHyx0rmZ Sorry for my inattentiveness. Yeah, I just meant to keep the Go interface the same, and hide all the HTTP async stuff behind the existing interfaces. The latest changes look great! I left one comment around the backoff.

2017-08-16 00:36 UTC, vito commented on client/volume_future.go
> +				time.Sleep(time.Duration(rand.Intn((1<<backoffFactor)-1)) * time.Second)
Seconds may be a bit too long. How about a baseline of 10ms, just to make something up? I figure at least in the common case of creating an empty volume it should complete really quickly.

I'd recommend taking a look at https://github.com/cenkalti/backoff - we use it elsewhere and is easier to use at a high level. See https://godoc.org/github.com/cenkalti/backoff#ExponentialBackOff

2017-08-16 02:03 UTC, SHyx0rmZ commented
Haha, don't worry. I also took my sweet time 😆

2017-08-28 16:11 UTC, merged

2017-08-28 16:12 UTC, vito commented
Tried out TestFlight and it takes the same amount of time as before. Thanks!

2017-08-28 16:38 UTC, SHyx0rmZ commented
Happy to hear! Thanks for all the feedback!